import Providers from "@/components/Providers"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Navbar from "@/components/Navbar"
import { Login } from "./login-page"
import { Popular } from "./popular-page"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} pt-8 pb-24 px-4 md:px-32`}>
        <Providers>
          <Navbar />
          <Popular></Popular>
          {/* {children} */}
        </Providers>
      </body>
    </html>
  )
}
